export const Slide = [
  {
    slug: "acs-ict-decoder-2026",
    title: "Completely For FREE",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1738987523/dec_ikpys3.webp",
    alt: "ACS FREE ICT DECODER 2026 & 2025 Archive",
    tag: "ICT Decoder 26 FREE"
  },
  {
    slug: "acs-final-revision-batch-2025-science",
    title: "GET it for 299 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218654/Frb25_hhccka.webp",
    alt: "Acs Final Revision Batch 2025, Science - Classes Lecture & Practice Sheets",
    tag: "FRB 2025 acs"
  },
  {
    slug: "acs-varsity-private-batch-2024",
    title: "acs varsity 2024 for 499 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218902/var_bai4aw.webp",
    alt: "Acs Varsity Private Batch 2024 - Classes Lecture & Practice Sheets",
    tag: "ACS varsity 2024"
  },
  {
    slug: "acs-engineering-private-batch-2024",
    title: "acs engineering 2024 for 499 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/eng24_odmkog.webp",
    alt: "ACS Engineering Private Batch 2024 - Classes Lecture & Practice Sheets",
    tag: "ACS Engineering 2024"
  },
  {
    slug: "acs-physics-all-cycles-2026",
    title: "physics all cycles 2026 for 799 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    alt: "Acs Physics All Cycles 2026 with 2025 archive - Classes Lecture & Practice Sheets",
    tag: "Physics cycles 26 acs"
  },
  {
    slug: "acs-chemistry-all-cycles-2026",
    title: "chemistry all cycles 2026 for 799 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    alt: "Acs Chemistry All Cycles 2026 with 2025 archive - Classes Lecture & Practice Sheets",
    tag: "Chemistry cycles 26 acs"
  },
  {
    slug: "acs-math-all-cycles-2026",
    title: "math all cycles 2026 for 799 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    alt: "Acs Math All Cycles 2026 with 2025 archive - Classes Lecture & Practice Sheets",
    tag: "Math cycles 26 acs"
  },
  {
    slug: "acs-biology-all-cycles-2026",
    title: "Biology all cycles 2026 for 799 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    alt: "Acs Biology All Cycles 2026 with 2025 archive - Classes Lecture & Practice Sheets",
    tag: "Biology cycles 26 acs"
  },
];

export const Files = [
  {
    slug: "acs-engineering-private-batch-2024", // SEO-friendly URL slug
    year: 2024,
    type: "Admission", // Broader category for search intent
    status: "Running",
    name: "ACS Engineering Private Batch 2024",
    subtitle:
      "ACS Engineering full course 2024 for 499 taka only full webapp access", // Secondary headline for SEO
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/eng24_odmkog.webp",
      alt: "ACS Engineering Private Batch 2024 - Classes Lecture & Practice Sheets", // ALT text for images (essential for SEO)
    },
    description: `
       ACS Engineering Course 2024 for Buet, KUET, RUET, CUET and other Public Engineering Admission Test.
    `,
    features: [
      "GET Access all latest classes, as well as previous years archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2024 & 2025 Buet Admission test", // Helps SEO and targeting
    price: 499,
    tags: [
      "Classes 140+",
      "Webapp recorded",
      "2023 full archive",
      "study materials",
    ],

    seo: {
      metaTitle: "ACS Engineering Private Batch 2024 - ACS Shop",
      metaDescription:
        "ACS Engineering Private Batch 2024. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only",
      keywords: [
        "ACS Engineering Course 2024",
        "BUET Admission 2024",
        "Recorded ACS Engineering Classes",
        "ACS Engineering Lectures",
        "ACS Engineering Practice Sheets",
        "Udvash Engineering 2024",
        "Acs Engineering",
        "Buet Admission",
        "Udvash Admission",
        "Apars Classroom",
        "Engineering Acs Shop",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 2024",
        "HSC 2025",
        "HSC 2026",
        "HSC Academic",
        "HSC Admission",
        "Dhaka University",
        "BUET Admission",
        "KUET Admission",
        "RUET Admission",
        "CUET Admission",
        "Private Engineering Admission",
        "Public Engineering Admission",
        "ROOTS EDU Engineering",
        "Apple Course ACS",
        "Apple store",
      ],
    },
  },
  {
    slug: "acs-varsity-private-batch-2024",
    year: 2024,
    type: "Admission",
    status: "Running",
    name: "Acs Varsity Private Batch 2024",
    subtitle:
      "ACS Varsity full course 2024 for 499 taka only full webapp access", // Secondary headline for SEO
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218902/var_bai4aw.webp",
      alt: "ACS Varsity Private Batch 2024 - Classes Lecture & Practice Sheets", // ALT text for images (essential for SEO)
    },
    description: `
       ACS Varsity Course 2024 for Dhaka, Chittagong, Rajshahi and other Public University + GST Admission Test.
    `,

    features: [
      "GET Access all latest classes, as well as previous years archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience:
      "FOR HSC 2024 & 2025 Dhaka, Chittagong, Rajshahi and other Public University + GST Admission Test", // Helps SEO and targeting
    price: 499,
    tags: [
      "Classes 140+",
      "Webapp recorded",
      "2023 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "ACS Varsity Private Batch 2024 - ACS Shop",
      metaDescription:
        "ACS Varsity Private Batch 2024. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only",
      keywords: [
        "ACS Varsity Course 2024",
        "Dhaka University Admission 2024",
        "Recorded ACS Varsity Classes",
        "ACS Varsity Lectures",
        "ACS Varsity Practice Sheets",
        "Udvash Varsity 2024",
        "Acs Varsity",
        "Dhaka University",
        "Udvash Admission",
        "Apars Classroom",
        "Engineering Acs Shop",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 2024",
        "HSC 2025",
        "HSC 2026",
        "HSC Academic",
        "HSC Admission",
        "Dhaka University",
        "BUET Admission",
        "KUET Admission",
        "RUET Admission",
        "CUET Admission",
        "Private University Admission",
        "Public University Admission",
        "ROOTS EDU University",
        "Apple Course ACS",
        "Apple store",
        "Udvash Ka Unit",
        "DU Ka Unit",
        "DU Admission",
        "GST Admission",
        "GST Admission 2024",
        "GST Admission 2025",
        "Varsity ka unit",
      ],
    },
  },
  {
    slug: "acs-final-revision-batch-2025-science",
    year: 2025,
    type: "academic",
    status: "running",
    name: "Acs Final Revision Batch 2025, Science",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218654/Frb25_hhccka.webp",
      alt: "Acs Final Revision Batch 2025, Science - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Final Revision Batch 2025, Science. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 299 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as previous years archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2025 Final Revision Science", // Helps SEO and targeting
    price: 299,
    tags: [
      "Classes 130+",
      "Webapp recorded",
      "2024 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Final Revision Batch 2025, Science - ACS Shop",
      metaDescription:
        "Acs Final Revision Batch 2025, Science. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 299 Taka only",
      keywords: [
        "Acs Final Revision Batch 2025, Science",
        "HSC 2025 Final Revision Science",
        "Acs Final Revision",
        "Acs Shop",
        "ACS Bangladesh",
        "HSC 25",
        "FRB 25",
        "FRB Science",
        "FRB 2025",
        "FRB lectures",
        "FRB lecture sheets",
        "ACS FRB 25",
        "ACS FRB 25 webapp",
        "ACS FRB 25 webapp access",
        "HSC FRB 25",
        "FRB Archive",
        "2024 FRB Archive",
        "ACS Shop FRB 25",
        "ACS Shop FRB 25 webapp",
        "ACS Shop FRB 25 webapp access",
        "HSC FRB 25",
        "HSC FRB 25 webapp",
        "HSC FRB 25 webapp access",
        "FRB BD",
        "FRB Bangla",
      ],
    },
  },
  {
    slug: "acs-physics-all-cycles-2025",
    year: 2025,
    type: "academic",
    status: "running",
    name: "Acs Physics All Cycles 2025",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218896/HSC-25_kmodpt.webp",
      alt: "Acs Physics All Cycles 2025 - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Physics All Cycles 2025. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as previous years archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2025 Physics All Cycles", // Helps SEO and targeting
    price: 499,
    tags: [
      "Classes 170+",
      "Webapp recorded",
      "Exam website",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Physics All Cycles 2025 - ACS Shop",
      metaDescription:
        "Acs Physics All Cycles 2025. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only",
      keywords: [
        "Acs Physics All Cycles 2025",
        "HSC 2025 Physics All Cycles",
        "Acs Physics",
        "Acs Shop",
        "ACS Bangladesh",
        "HSC 25",
        "Physics All Cycles",
        "ACS Physics Cycle 1",
        "ACS Physics Cycle 2",
        "ACS Physics Cycle 3",
        "ACS Physics Cycle 4",
        "ACS Physics Cycle 5",
        "ACS Physics Cycle 6",
        "ACS Cycle 2025",
        "ACS Physics 25",
        "ACS Physics 2025",
        "ACS Physics 2025 webapp",
        "ACS Physics 2025 webapp access",
        "ACS Physics 2025 webapp download",
        "ACS Physics 2025 webapp download",
        "ACS Physics cycle 2026",
      ],
    },
  },
  {
    slug: "acs-chemistry-all-cycles-2025",
    year: 2025,
    type: "academic",
    status: "running",
    name: "Acs Chemistry All Cycles 2025",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218859/chee1_f8yzwe.jpg",
      alt: "Acs Chemistry All Cycles 2025 - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Chemistry All Cycles 2025. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as previous years archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2025 Chemistry All Cycles", // Helps SEO and targeting
    price: 499,
    tags: [
      "Classes 170+",
      "Webapp recorded",
      "Exam website",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Chemistry All Cycles 2025 - ACS Shop",
      metaDescription:
        "Acs Chemistry All Cycles 2025. Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only",
      keywords: [
        "Acs Chemistry All Cycles 2025",
        "HSC 2025 Chemistry All Cycles",
        "Acs Chemistry",
        "Acs Shop",
        "ACS Bangladesh",
        "HSC 25",
        "Chemistry All Cycles",
        "ACS Chemistry All Cycles",
        "ACS Chemistry All Cycles webapp",
        "ACS Chemistry All Cycles webapp access",
        "ACS Chemistry All Cycles webapp download",
        "ACS Chemistry All Cycles webapp download",
        "ACS Chemistry All Cycles cycle 2026",
      ],
    },
  },
  {
    slug: "bp-english-winner-4.0",
    year: 2025,
    type: "academic",
    status: "completed",
    name: "BP Engish Winner 4.0",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/e4_mowc5r.webp",
      alt: "BP Engish Winner 4.0 - Classes Lecture & Practice Sheets",
    },
    description: `
       BP Engish Winner 4.0. All Recorded classes, Lecture & Practice Sheets with English winner 3.0 archive. Enroll now for 299 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as English winner 3.0 archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2025 & 2026 English Winner 4.0", // Helps SEO and targeting
    price: 299,
    tags: [
      "Classes 50+",
      "Webapp recorded",
      "3.0 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "BP Engish Winner 4.0 - Bondi Pathshala",
      metaDescription:
        "BP Engish Winner 4.0. All Recorded classes, Lecture & Practice Sheets with English winner 3.0 archive. Enroll now for 299 Taka only",
      keywords: [
        "BP Engish Winner 4.0",
        "HSC 2025 English Winner 4.0",
        "HSC 2026 English Winner 4.0",
        "English Winner 4.0",
        "Bondi Pathshala English Winner 4.0",
        "বন্দি পাঠশালা English Winner 4.0",
        "English Winner 5.0",
        "Bondi Pathshala English Winner 5.0",
        "বন্দি পাঠশালা English Winner 5.0",
      ],
    },
  },
  {
    slug: "bp-organic-chemistry-2.0",
    year: 2025,
    status: "completed",
    type: "academic",
    name: "BP Organic Chemistry 2.0",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218905/BPorg2_r3hcpp.webp",
      alt: "BP Organic Chemistry 2.0 - Classes Lecture & Practice Sheets",
    },
    description: `
       BP Organic Chemistry 2.0. All Recorded classes, Lecture & Practice Sheets with Organic Chemistry 1.0 archive. Enroll now for 299 Taka only
    `,
    features: [
      "GET Access all latest classes(No archive) anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 299,
    tags: ["Classes 50+", "Webapp recorded", "Exam website", "study materials"],
    seo: {
      metaTitle: "BP Organic Chemistry 2.0 - Bondi Pathshala",
      metaDescription:
        "BP Organic Chemistry 2.0. All Recorded classes, Lecture & Practice Sheets with Organic Chemistry 1.0 archive. Enroll now for 299 Taka only",
      keywords: [
        "BP Organic Chemistry 2.0",
        "HSC 2025 Organic Chemistry 2.0",
        "HSC 2026 Organic Chemistry 2.0",
        "Organic Chemistry 2.0",
        "Bondi Pathshala Organic Chemistry 2.0",
        "বন্দি পাঠশালা Organic Chemistry 2.0",
      ],
    },
  },

  {
    slug: "ictdecoder26",
    year: 2026,
    status: "completed",
    type: "academic",
    name: "Acs Ict Decoders 2026",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1738987523/dec_ikpys3.webp",
      alt: "Acs Ict Decoders 2026 + HSC 2025 archive - Classes Lecture & Practice Sheets",
    },
    description: `
       Acs Ict Decoders 2026. All Recorded classes, Lecture & Practice Sheets with Archive, completely for FREE
    `,
    features: [
      "GET Access all latest ICT Decoder 2026 classes anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Lecture & practice sheets available (free)",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
    ],
    assurance: [
      "No Payment required",
      "No dedicated support",
      "No extra features",
    ],
    targetAudience: "FOR HSC 2026 Ict Decoders", // Helps SEO and targeting
    price: "free",
    tags: ["Classes 45+", "Webapp recorded", "2025 archive", "study materials"],
    seo: {
      metaTitle: "Acs Ict Decoders 2025 - ACS Shop",
      metaDescription:
        "Acs Ict Decoders 2025. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 499 Taka only",
      keywords: [
        "Acs Ict Decoders 2026",
        "HSC 2026 Ict Decoders",
        "Acs Ict",
        "Acs Shop",
        "ACS Bangladesh",
        "HSC 26",
        "Ict Decoders",
        "Acs Ict Decoders 2026 webapp",
        "Acs Ict Decoders 2026 webapp access",
        "Acs Ict Decoders 2026 webapp download",
        "Acs Ict Decoders 2026 webapp download",
        "Acs Ict Decoders 2025 webapp download",
        "ACS HSC 26 cycles",
        "ICT Archive 25",
      ],
    },
  },
  {
    slug: "frb-archive-2024",
    year: 2024,
    status: "completed",
    type: "academic",
    name: "Final Revision Batch 2024",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218863/frb_zqucyi.webp",
      alt: "Final Revision Batch 2024 FREE - Classes Lecture & Practice Sheets",
    },
    description: `
       Final Revision Batch 2024. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll for free
    `,
    features: [
      "GET Access all to Final Revision Batch 2024 and Materials, completely for free anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "No downloadable classes but lectures and practice sheets are available for free",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
    ],
    assurance: [
      "No Payment required",
      "No dedicated support",
      "No extra features",
    ],
    price: "free",
    tags: [
      "Classes 100+",
      "Webapp recorded",
      "Science Sub Only",
      "study materials",
    ],
    seo: {
      metaTitle: "Final Revision Batch 2024 FREE - ACS Shop",
      metaDescription:
        "Final Revision Batch 2024. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll for free",
      keywords: [
        "Final Revision Batch 2024",
        "HSC 2024 Final Revision Batch",
        "Final Revision Batch 2024 Free",
        "Final Revision Batch 2024 Free Access",
        "Final Revision Batch 2024 Free Download",
        "Final Revision Batch 2024 Free Download",
        "FRB 2024",
        "FRB 2024 Free",
        "FRB 2024 Free Access",
        "FRB 2024 Free",
        "ACS FRB 2024",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 24",
        "FRB 2025",
        "ACS FRB 2025",
        "ACS Shop FRB 2025",
        "ACS Bangladesh FRB 2025",
        "HSC 25",
      ],
    },
  },
  {
    slug: "acs-physics-all-cycles-2026",
    year: 2026,
    status: "running",
    type: "academic",
    name: "Acs Physics All Cycles 2026",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
      alt: "Acs Physics All Cycles 2026 - Classes Lecture & Practice Sheets",
    },
    description: `
       Acs Physics All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only
    `,
    features: [
      "GET Access all latest Acs Physics All Cycles 2026 classes and 2025 archive anytime, anywhere.",
      "Includes all chapters both 1st & 2nd paper",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable classes, lectures and practice sheets",
      "Recorded Class - Same day upload! & regular updates and maintenance",
      "All Archive from 2025 are already uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Physics All Cycles 2026 - ACS Shop",
      metaDescription:
        "Acs Physics All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only",
      keywords: [
        "Acs Physics All Cycles 2026",
        "HSC 2026 Physics All Cycles",
        "ACS Cycles 2026",
        "ACS Physics 2026",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "Acs Physics All Cycles 2026 webapp access",
        "ACS Physics cycle 1 2026",
        "ACS Physics cycle 2 2026",
        "ACS Physics cycle 3 2026",
        "ACS Physics cycle 4 2026",
        "ACS Physics cycle 5 2026",
        "Apurba Apu Physics 2026",
        "Apar Classroom Physics 2026",
        "ACS All cycles 2026",
        "HSC Physics cycle 2026",
        "HSC Physics",
        "ACS Apurba Apu Physics 2026",
        "ACS all cycles combined 2026",
      ],
    },
  },
  {
    slug: "acs-chemistry-all-cycles-2026",
    year: 2026,
    status: "running",
    type: "academic",
    name: "Acs Chemistry All Cycles 2026",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
      alt: "Acs Chemistry All Cycles 2026 - Classes Lecture & Practice Sheets",
    },
    description: `
       Acs Chemistry All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only
    `,
    features: [
      "GET Access all latest Acs Chemistry All Cycles 2026 classes and 2025 archive anytime, anywhere.",
      "Includes all chapters both 1st & 2nd paper",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable classes, lectures and practice sheets",
      "Recorded Class - Same day upload! & regular updates and maintenance",
      "All Archive from 2025 are already uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Chemistry All Cycles 2026 - ACS Shop",
      metaDescription:
        "Acs Chemistry All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only",
      keywords: [
        "Acs Chemistry All Cycles 2026",
        "HSC 2026 Chemistry All Cycles",
        "ACS Chemistry 2026",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "Acs Chemistry All Cycles 2026 webapp access",
        "Organic Chemistry 2026",
        "ACS Chemistry cycle 1 2026",
        "ACS Chemistry cycle 2 2026",
        "ACS Chemistry cycle 3 2026",
        "ACS Chemistry cycle 4 2026",
        "ACS Chemistry cycle 5 2026",
        "Sonjoy Chemistry 2026",
        "Apar Classroom Chemistry 2026",
        "HSC 2026 Chemistry Cycles",
        "HSC 2026 Chemistry",
        "HSC 2026 Chemistry All Cycles",
        "HSC 2026 Chemistry All Cycles",
        "ACS Chemistry",
        "Nazmus Sakib Chemistry 2026",
        "ACS Chemistry all cycles combined 2026",
      ],
    },
  },
  {
    slug: "acs-math-all-cycles-2026",
    year: 2026,
    status: "running",
    type: "academic",
    name: "Acs Math All Cycles 2026",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
      alt: "Acs Math All Cycles 2026 - Classes Lecture & Practice Sheets",
    },
    description: `
       Acs Math All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only
    `,
    features: [
      "GET Access all latest Acs Math All Cycles 2026 classes and 2025 archive anytime, anywhere.",
      "Includes all chapters both 1st & 2nd paper",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable classes, lectures and practice sheets",
      "Recorded Class - Same day upload! & regular updates and maintenance",
      "All Archive from 2025 are already uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Math All Cycles 2026 - ACS Shop",
      metaDescription:
        "Acs Math All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only",
      keywords: [
        "Acs Math All Cycles 2026",
        "HSC 2026 Math All Cycles",
        "ACS Math 2026",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "Acs Math All Cycles 2026 webapp access",
        "ACS math cycle 1 2026",
        "ACS math cycle 2 2026",
        "ACS math cycle 3 2026",
        "ACS math cycle 4 2026",
        "ACS math cycle 5 2026",
        "HSC 2026 Math Cycles",
        "HSC 2026 Math",
        "HSC 2026 Math All Cycles",
        "Apar Classroom Math 2026",
        "ACS Math All Cycles 2026",
        "HSC 2026 Math",
        "HSC 2026 Math All Cycles",
        "HSC 2026 Math",
        "HSC 2026 Math All Cycles",
        "HSC 2026 Math",
        "HSC 2026 Math All Cycles",
        "ACS 2026 Math course",
        "HSC 2026 Math All Cycles",
      ],
    },
  },
  {
    slug: "acs-biology-all-cycles-2026",
    year: 2026,
    status: "running",
    type: "academic",
    name: "Acs Biology All Cycles 2026",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
      alt: "Acs Biology All Cycles 2026 - Classes Lecture & Practice Sheets",
    },
    description: `
       Acs Biology All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only
    `,
    features: [
      "GET Access all latest Acs Biology All Cycles 2026 classes and 2025 archive anytime, anywhere.",
      "Includes all chapters both 1st & 2nd paper",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable classes, lectures and practice sheets",
      "Recorded Class - Same day upload! & regular updates and maintenance",
      "All Archive from 2025 are already uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 799,
    tags: [
      "Cl asses 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "Acs Biology All Cycles 2026 - ACS Shop",
      metaDescription:
        "Acs Biology All Cycles 2026. All Recorded classes, Lecture & Practice Sheets with Archive. Enroll now for 799 Taka only",
      keywords: [
        "Acs Biology All Cycles 2026",
        "HSC 2026 Biology All Cycles",
        "ACS Biology 2026",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "Acs Biology All Cycles 2026 webapp access",
        "ACS Biology cycle 1 2026",
        "ACS Biology cycle 2 2026",
        "ACS Biology cycle 3 2026",
        "ACS Biology cycle 4 2026",
        "ACS Biology cycle 5 2026",
        "HSC 2026 Biology Cycles",
        "HSC 2026 Biology",
        "Hasnat shuvro Biology 2026",
        "Rajib vai Biology 2026",
        "Apar Classroom Biology 2026",
        "HSC 2026 Biology All Cycles",
        "HSC 2026 Biology",
        "HSC 2026 Biology All Cycles",
        "HSC 2026 Biology",
        "HSC 2026 Biology All Cycles",
        "ACS Biology All Cycles combined 2026",
      ],
    },
  },
  {
    slug: "english-winner-4.0",
    year: 2026,
    status: "completed",
    type: "academic",
    name: "english winner 4.0",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/e4_mowc5r.webp",
      alt: "BP Engish Winner 4.0 - Classes Lecture & Practice Sheets",
    },
    description: `
       BP Engish Winner 4.0. All Recorded classes, Lecture & Practice Sheets with English winner 3.0 archive. Enroll now for 299 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as English winner 3.0 archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - Same day upload!",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    targetAudience: "FOR HSC 2025 & 2026 English Winner 4.0", // Helps SEO and targeting
    price: 299,
    tags: [
      "Classes 50+",
      "Webapp recorded",
      "3.0 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "BP Engish Winner 4.0 - Bondi Pathshala",
      metaDescription:
        "BP Engish Winner 4.0. All Recorded classes, Lecture & Practice Sheets with English winner 3.0 archive. Enroll now for 299 Taka only",
      keywords: [
        "BP Engish Winner 4.0",
        "HSC 2025 English Winner 4.0",
        "HSC 2026 English Winner 4.0",
        "English Winner 4.0",
        "Bondi Pathshala English Winner 4.0",
        "বন্দি পাঠশালা English Winner 4.0",
        "English Winner 5.0",
        "Bondi Pathshala English Winner 5.0",
        "বন্দি পাঠশালা English Winner 5.0",
      ],
    },
  },
  {
    slug: "acs-physics-cycle-01",
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs physics cycle 01",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218900/pc1_g2ratu.jpg",
      alt: "ACS Physics Cycle 01 - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Physics Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as 2025 archive anytime, anywhere.",
      "Includes 3 chapters and their archive",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - with 2025 archive uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "ACS Physics Cycle 01 - ACS Shop",
      metaDescription:
        "ACS Physics Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only",
      keywords: [
        "ACS Physics Cycle 01",
        "HSC 2026 Physics Cycle 01",
        "ACS Physics Cycle 01",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "ACS Physics cycle 01 webapp access",
        "ACS Physics cycle 01 2026",
        "HSC 2026 Physics Cycle 01",
      ],
    },
  },
  {
    slug: "acs-chemistry-cycle-01",
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs chemistry cycle 01",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218906/cc1_t3iohj.webp",
      alt: "ACS Chemistry Cycle 01 - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Chemistry Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as 2025 archive anytime, anywhere.",
      "Includes 3 chapters and their archive",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - with 2025 archive uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "ACS Chemistry Cycle 01 - ACS Shop",
      metaDescription:
        "ACS Chemistry Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only",
      keywords: [
        "ACS Chemistry Cycle 01",
        "HSC 2026 Chemistry Cycle 01",
        "ACS Chemistry Cycle 01",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "ACS Chemistry cycle 01 webapp access",
        "ACS Chemistry cycle 01 2026",
      ],
    },
  },
  {
    slug: "acs-math-cycle-01",
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs math cycle 01",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218906/c1_ijspga.jpg",
      alt: "ACS Math Cycle 01 - Classes Lecture & Practice Sheets",
    },
    description: `
       ACS Math Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only
    `,
    features: [
      "GET Access all latest classes, as well as 2025 archive anytime, anywhere.",
      "Includes 3 chapters and their archive",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - with 2025 archive uploaded",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "ACS Math Cycle 01 - ACS Shop",
      metaDescription:
        "ACS Math Cycle 01. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 250 Taka only",
      keywords: [
        "ACS Math Cycle 01",
        "HSC 2026 Math Cycle 01",
        "ACS Math Cycle 01",
        "ACS Shop",
        "ACS Bangladesh",
        "HSC 26",
        "ACS Math cycle 01 webapp access",
        "ACS Math cycle 01 2026",
      ],
    },
  },
  {
    slug: "bp-hsc-powerplay-2025-2024-archive",
    year: 2025,
    status: "running",
    type: "academic",
    name: "BP HSC Powerplay 2025 + 2024 archive",
    image: {
      url: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732220695/169k_m8ofii.webp",
      alt: "BP HSC Powerplay 2025 + 2024 archive - Classes Lecture & Practice Sheets",
    },
    features: [
      "GET Access all latest classes, as well as 2024 archive anytime, anywhere.",
      "যতো ইচ্ছে ততো Device access, No restrictions",
      "Downloadable Classes, Lectures & Practice Sheets",
      "Recorded Class - same day upload! & regular updates and maintenance",
      "Lightning-fast webapp, which you can Install as a Mobile or a Desktop App",
      "No social media distractions with a dedicated WEBAPP.",
      "High Quality Video & Audio Streaming without extensive usesage of Data",
      "Instant access! within 3 minutes of payment confirmation.",
    ],
    assurance: [
      "100% Money Back Guarantee within 20 minutes of payment, If you are not satisfied ",
      "24/7 support through Facebook Messenger & Facebook Group for uninterrupted help.",
      "Our developers can do anything and everything, So কোনো extra feature প্রয়োজন হলে just ask করবে।",
    ],
    price: 499,
    tags: [
      "Classes 130+",
      "Webapp recorded",
      "2024 full archive",
      "study materials",
    ],
    seo: {
      metaTitle: "BP HSC Powerplay 2025 + 2024 archive - Bondi Pathshala",
      metaDescription:
        "BP HSC Powerplay 2025 + 2024 archive. All Recorded classes, Lecture & Practice Sheets with 2025 archive. Enroll now for 499 Taka only",
      keywords: [
        "BP HSC Powerplay 2025 + 2024 archive",
        "HSC 2025 Powerplay",
        "HSC 2026 Powerplay",
        "Bondi Pathshala Powerplay",
        "বন্দি পাঠশালা Powerplay",
      ],
    },
  },
];

export function getProduct(slug) {
  return Files.find((data) => data.slug === slug);
}
