export const Slide = [
  {
    id: 3,
    title: "GET it for 299 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218654/Frb25_hhccka.webp",
  },
  {
    id: 2,
    title: "acs varsity 2024 for 499 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218902/var_bai4aw.webp",
  },
  {
    id: 1,
    title: "acs engineering 2024 for 499 only",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/eng24_odmkog.webp",
  },
  {
    id: 10,
    title: "physics all cycles 2026 for 799 only",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
  },
  {
    id: 11,
    title: "chemistry all cycles 2026 for 799 only",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
  },
  {
    id: 12,
    title: "math all cycles 2026 for 799 only",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
  },{
    id: 13,
    title: "Biology all cycles 2026 for 799 only",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
  },


];

export const Files = [
  {
    id: 1,
    year: 2024,
    type: "admission",
    status: "running",
    name: "Acs Engineering Private Batch 2024",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/eng24_odmkog.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 499,
    tags: [
      "Classes 140+",
      "Webapp recorded",
      "2023 full archive",
      "study materials",
    ],
  },
  {
    id: 2,
    year: 2024,
    status: "running",
    type: "admission",
    name: "Acs Varsity Private Batch 2024",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218902/var_bai4aw.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 499,
    tags: [
      "Classes 140+",
      "Webapp recorded",
      "2023 full archive",
      "study materials",
    ],
  },
  {
    id: 3,
    year: 2025,
    status: "running",
    type: "academic",
    name: "acs final revision batch(FRB) 2025 Science",
    image:
      "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218654/Frb25_hhccka.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 299,
    tags: [
      "Classes 130+",
      "Webapp recorded",
      "2024 full archive",
      "study materials",
    ],
  },
  {
    id: 4,
    year: 2025,
    status: "running",
    type: "academic",
    name: "Acs Physics All Cycles 2025",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218896/HSC-25_kmodpt.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 499,
    tags: [
      "Classes 170+",
      "Webapp recorded",
      "Exam website",
      "study materials",
    ],
  },
  {
    id: 5,
    year: 2025,
    status: "running",
    type: "academic",
    name: "Acs Chemistry All Cycles 2025",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218859/chee1_f8yzwe.jpg",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 499,
    tags: [
      "Classes 170+",
      "Webapp recorded",
      "Exam website",
      "study materials",
    ],
  },
  {
    id: 6,
    year: 2025,
    status: "completed",
    type: "academic",
    name: "BP Engish Winner 4.0",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/e4_mowc5r.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 299,
    tags: [
      "Classes 50+",
      "Webapp recorded",
      "3.0 full archive",
      "study materials",
    ],
  },
  {
    id: 7,
    year: 2025,
    status: "completed",
    type: "academic",
    name: "BP Organic Chemistry 2.0",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218905/BPorg2_r3hcpp.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 299,
    tags: ["Classes 50+", "Webapp recorded", "Exam website", "study materials"],
  },
  {
    id: 8,
    year: 2025,
    status: "completed",
    type: "academic",
    name: "acs ict decoders 2025",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218898/ict_zb3jlz.jpg",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না",
      "Classes & PDFs Download করতে পারবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "No Support for this course",
      "Instant access, NO payment required",
    ],
    price: "free",
    tags: ["Classes 45+", "Webapp recorded", "Exam website", "study materials"],
  },
  {
    id: 9,
    year: 2025,
    status: "completed",
    type: "academic",
    name: "Final Revision Batch 2024",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218863/frb_zqucyi.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না",
      "Classes & PDFs Download করতে পারবে।",
      "Updates, Not so frequent",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "No Support for this course",
      "Instant access, NO payment required",
      "FREE Lectures & Practice Sheets",
    ],
    price: "free",
    tags: [
      "Classes 100+",
      "Webapp recorded",
      "Science Sub Only",
      "study materials",
    ],
  },
  {
    id: 10,
    year: 2026,
    status: "running",
    type: "academic",
    name: "acs physics all cycles 2026",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Includes all chapters both 1st & 2nd paper",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে। [Uploaded already]",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 11,
    year: 2026,
    status: "running",
    type: "academic",
    name: "acs chemistry all cycles 2026",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Includes all chapters both 1st & 2nd paper",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে। [Uploaded already]",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 12,
    year: 2026,
    status: "running",
    type: "academic",
    name: "acs math all cycles 2026",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Includes all chapters both 1st & 2nd paper",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে। [Uploaded already]",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 13,
    year: 2026,
    status: "running",
    type: "academic",
    name: "acs biology all cycles 2026",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218700/hsc26_zrernc.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Includes all chapters both 1st & 2nd paper",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে। [Uploaded already]",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 799,
    tags: [
      "Classes 250+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 14,
    year: 2026,
    status: "completed",
    type: "academic",
    name: "english winner 4.0",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218862/e4_mowc5r.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Includes all chapters both 1st & 2nd paper",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive 3.0 (classes & materials) থাকবে। [Uploaded already]",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 299,
    tags: [
      "Classes 50+",
      "Webapp recorded",
      "3.0 full archive",
      "study materials",
    ],
  },
  {
    id: 15,
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs physics cycle 01",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218900/pc1_g2ratu.jpg",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 16,
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs chemistry cycle 01",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218906/cc1_t3iohj.webp",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
  {
    id: 17,
    year: 2026,
    status: "completed",
    type: "academic",
    name: "acs math cycle 01",
    image: "https://res.cloudinary.com/dcxmbqwzo/image/upload/v1732218906/c1_ijspga.jpg",
    demo: "",
    features: [
      "Class গুলো Live করতে পারবে না। Recorded করতে হবে।",
      "Course এর Exams গুলো দিতে পারবে না, Just Solution PDFs পাবে।",
      "Exam এর জন্য Alternate Site provide করা হবে।",
      "Classes & PDFs Download করতে পারবে।",
      "Regular updates",
      "Previous year এর archive(classes & materials) থাকবে।",
      "Course এর সকল Content আমাদের lightning fast WEBAPP এ থাকবে SO, Soicial media TimeWaste এর possibility নেই।",
      "আমাদের WEBAPP যেকোনো regular app এর চেয়ে 10X Faster.",
      "24/7 Support on Facebook messenger.",
      "Instant access, usually pay করার 3mins এর মধ্যেই।",
    ],
    price: 250,
    tags: [
      "Classes 40+",
      "Webapp recorded",
      "2025 full archive",
      "study materials",
    ],
  },
];
